#config-version=FG201F-7.4.4-FW-build2662-240418:opmode=0:vdom=0:user=fg
#conf_file_ver=30103082929
#buildno=2662
#global_vdom=1
config system global
    set admin-sport 7443
    set hostname "TWCH-HQ2-201F-01"
    set timezone 68
end
config system accprofile
    edit "reviewer"
        set secfabgrp read
        set ftviewgrp read
    next
end
config system admin
    edit "fg"
        set old-password ENC SH2tSyQoUBbJYUuFyxirFUJ4hrkmSfDL0Zo+9FNeHjZ3XTUg0bqYBOHwQ72H0M=
        set trusthost1 192.168.250.1 255.255.255.255
        set trusthost2 172.16.5.0 255.255.255.0
        set trusthost3 192.168.224.0 255.255.224.0
        set trusthost4 10.240.29.254 255.255.255.255
        set accprofile "super_admin"
        set vdom "root"
        set gui-ignore-release-overview-version "7.4"
        set password ENC PB2Kj2um6+rPQMCqR87K0nYcoe9OyDabPm3uppQSXn5OFamOTZ3mtgEw76KmYERpKimyadKL7QRCt8j6jyS9dpJ0pkbR9w7Jbt0vba3mNnXstE=
    next
    edit "twspadmin"
        set old-password ENC SH2FlKfT9zWFFLMGikpqMhe7CbrVa9bXsdSF8KrVEwcZ6cQWsh0Ho5cQH1U0B8=
        set trusthost1 172.16.3.68 255.255.255.255
        set trusthost2 172.16.5.124 255.255.255.255
        set trusthost3 172.16.5.50 255.255.255.255
        set trusthost4 172.22.208.108 255.255.255.255
        set trusthost5 172.16.5.125 255.255.255.255
        set accprofile "reviewer"
        set vdom "root"
        set password ENC PB2gWyf05M2o5Ysc7zzDQ0kFcuI+tkV3uhyC5rptzULaErGqXKN+tc14PAzdHZw+75yLcr94Ow/KNUSTXbk78S7AUScSFAEPBnzXE8Tj76kbks=
    next
    edit "Tacacs_admin"
        set remote-auth enable
        set trusthost1 172.16.5.0 255.255.255.0
        set trusthost2 118.163.189.205 255.255.255.255
        set trusthost3 172.16.0.254 255.255.255.255
        set trusthost4 10.240.29.254 255.255.255.255
        set trusthost5 192.168.224.0 255.255.224.0
        set trusthost6 172.16.0.0 255.255.255.0
        set accprofile "super_admin"
        set vdom "root"
        config gui-dashboard
            edit 17
                set name "Status"
                set vdom "root"
                set permanent enable
                config widget
                    edit 1
                        set width 1
                        set height 1
                    next
                    edit 2
                        set type licinfo
                        set x-pos 1
                        set width 1
                        set height 1
                    next
                    edit 3
                        set type forticloud
                        set x-pos 2
                        set width 1
                        set height 1
                    next
                end
            next
            edit 18
                set name "Security"
                set vdom "root"
                config widget
                    edit 1
                        set type fortiview
                        set width 2
                        set height 1
                    next
                end
            next
        end
        set gui-default-dashboard-template "minimal"
        set gui-ignore-release-overview-version "7.4"
        set wildcard enable
        set remote-group "Tacacs-Admin"
    next
    edit "rogue_user"
        set accprofile "super_admin"
        set vdom "root"
    next
end
config system api-user
    edit "API_Read"
        set comments "TRQ202405080024TW"
        set api-key ENC SH29O3b8eZ1wre2iki9oACq4pgoZ+a7NS4FbpovlmOGni1UKDBzLwHGRRWq/Ec=
        set accprofile "reviewer"
        config trusthost
            edit 1
                set ipv4-trusthost 172.16.5.193 255.255.255.255
            next
        end
    next
    edit "rogue_api"
        set accprofile "super_admin"
        config trusthost
            edit 1
                set ipv4-trusthost 10.0.0.1 255.255.255.255
            next
        end
    next
end
config firewall policy
    edit 1
        set srcintf "port1"
        set dstintf "port2"
        set action accept
    next
end
